mutation CreatePR($repoID: ID!, $fromBranch: String!, $intoBranch: String = "develop", $title: String = "") {
  createPullRequest(input: {
    repositoryId: $repoID
    baseRefName: $intoBranch
    headRefName: $fromBranch
    title: $title
  }) {
    pullRequest {
      id
    }
  }
}
